
--PL/SQL NEDIR?
/*PROCEDURAL LANGUAGE EXTENSION TO STRUCTURED QUERY LANGUGE
SQL PROGRAMLAMA DILININ BIR DIZI KURALLARLA, YANI PROCEDUR OZELLIKLERIYLE DONATILMIS HALIDIR.
ORACLE VERITABANINA YERLESTIRILMIS UC TEMEL PROGRAMLAMA DILINDEN BIRIDIR.
BUNLAR SQL, JAVA VE PL/SQL'DIR.
PROCEDURAL(BUYRUKCU) YAPIYLA SQL'IN BIRBIRI ILE IC ICE KULLANIMINA PL/SQL DENIYOR.
YANI IF THEN ELSE, LOOPS, FUNCTIONS, PROCEDURE VS.. BIRLIKTE KULLANIMI.
PL/SQL VERITABANI SEVIYESINDE PROGRAMLAMA DILIDIR.(DATABASE LEVEL BACK-END PROGRAMMING)
TIPKI SQL KOMUTLARINDA OLDUGU GIBI, VERITABANI SEVIYESINDE YAZILAN PL/SQL PROGRAMLARI(STORED PROCEDURE, FUNCTION VS) TUM ARAYUZ PROGRAMLAMA DILLERINDEN(JAVA, C#, PYTHON, PHP VS.) CALISTIRILABILIR.
*/
--JAVA CLASS ICINDE PL/SQL CALISTIRMAYA ORNEK.
Connection conn = getConnection();
CallableStatement call = conn.prepareCall("{? = call MYFUNCTION(PARAM1, PARAM2, PARAM3)}");

--PL/SQL IN ICINDE JAVA CALISTIRMAYA ORNEK:
CREATE OR REPLACE FUNCTION TestCallJava(P_Text, IN VARCHAR2) RETURN VARCHAR2
AS
LANGUAGE JAVA NAME 'CallJava.WrFunc(java.lang.String) return java.lang.String'; --> JAVA KODU CALISTIRAN PL/SQL FOKNSIYONU
SELECT TestCallJava('Selamun Aleykum Dayý') FROM DUAL;
PL/SQL KONUSU KIMLERI ILGILENDIRIYOR.
RDBMS MIMARIDE VERITABANI KULLANILACAKSA;
MODULER, PERFORMANSLI VE BAKIM ONARIM MALIYETI DUSUK OLAN UYGULAMALAR GELISTIRMEK ISTEYEN TUM YAZILIMCILARI ILGILENDIRIR.
FARKLI TUREVLERI(MICROSOFT TSQL'I RESMEN PL/SQL'DEN CALDI KENDISI HIRSIZ BIR FIRMA!)
PL/SQL(ORACLE) --> T-SQL(MSSQL SERVER)
PL/pgSQL(POSTGRESQL DATABASE) --> GUZEL BIR DB BEN SEVIYORUM TAVSIYE EDIYORUM.

--PL/SQL STRUCTURE(KOD YAPISI)
DECLARE(ISTEGE BAGLI)
DEGISKENLER, SABITLER, CURSORLAR TANIMLAYABILIRIZ. BURASI TANIMLAMA ALANIDIR.
BEGIN(ZORUNLU)
PL/SQL EXECUTABLE STATEMENTS
EN AZ 1 TANE CALISTIRILABILIR KOD YAZILMALIDIR.
EXCEPTION(ISTEGE BAGLI)
BEGIN BLOGU ICINDE HATA OLUSABILIR BIR ISLEM VARSA ONU EXCEPTION BLOGUNDA ISLEMELIYIZ. PROGRAMI BIR SEKILDE DEVAM ETTIRMELIYIZ. 
END(ZORUNLU)

--PL/SQL BLOCK TURLERI
--UNNAMED BLOCK
--ISMI YOKTUR.
--VERITABANI ICINDE SAKLANAMAZ.
--CALISMA ESNASINDA DERLENIR(PARSING).
--BASKA PL/SQL BLOKLARINDAN YA DA ARAYUZ PROGRAMLAMA DILLERI ICINDEN CALISTIRILAMAZ.

--NAMED BLOCK
--ISMI VARDIR.
--VERITABANI ICINDE SAKLANIR.
--DERLENMIS HALI DAHA SONRADAN CAGRILIP CALISTIRILABILIR.
--BASKA PL/SQL BLOCKLARI VE ARAYUZ PROGRAMLAMA DILLERI ICERISINDEN CALISTIRILABILIR.


--TERMINAL
--SQLPLUS $ / AS SYSDBA; --> SYSDBA ROLE ILE LOGIN OLDUK.
SHOW USER; --> LOGIN OLDUGUMUZ KULLANICIYI VERIR.
SET SERVEROUTPUT ON; --> CIKTI VERMESINI AKTIF HALE GETIRDIK.
DECLARE 
    WMESSAGE VARCHAR2(100);
BEGIN
    WMESSAGE := 'MERHABALAR ARKADASIM PL SQL. BU ILK PROCEDURAL PROGRAMIMIM';
    DBMS_OUTPUT.PUT_LINE(WMESSAGE);
END;
ED; --> EDITOR SON YAZILAN KOMUTU NOTEPAD ILE ACAR DUZENLEMEMIZ ICINDIR.
--DUZENLENEN KOMUTU CALISTIRMAK ICIN / YAHUT R YAZIP CALISTIRCAZ. R RUN DEMEKTIR.
--HR KULLANICISI DIYE BIR KULLANICI VAR KURULUM ESNASINDA GELDI.
--BU KULLANICI ILE LOGIN OLMAYA CALISINCA KILITLIDIR HATASI ALIYORUZ.
--KILIDI KALDIRMAK ICIN ISE SYSDBA ROLU OLAN BIR KULLANICI ILE BAGLANMAK LAZIM.
--SYS AS SYSDBA; LOGIN OLMAK LAZIMDIR.
SHOW USER;
ALTER USER HR IDENTIFIED BY HR ACCOUNT UNLOCK; --> HESAP KILIDINI KALDIRDIK.
--ISIMSIZ BLOCK:
SET SERVEROUTPUT ON;
DECLARE
    WGUN VARCHAR2(50);
BEGIN
    WGUN := GET_DAY_NAME(SYSDATE);
    DBMS_OUTPUT.PUT_LINE(WGUN);
END;
--ISIMLI BLOCK
CREATE OR REPLACE FUNCTION GET_DAY_NAME(p_tarih DATE)RETURN VARCHAR2
IS

BEGIN
    RETURN(TO_CHAR(p_tarih, 'DAY'));
END;

SELECT GET_DATE_NAME(SYSDATE) FROM DUAL;





























_