SELECT USERNAME, SID, SERIAL#, TYPE
FROM V$SESSION
WHERE TYPE <> 'BACKGROUND';

SELECT DR.GRANTEE
FROM DBA_SYS_PRIVS DS, DBA_ROLE_PRIVS DR
WHERE DS.PRIVILEGE = 'RESTRICTED SESSION'
AND DS.GRANTEE = DR.GRANTED_ROLE
UNION
SELECT USERNAME
FROM DBA_SYS_PRIVS DS, DBA_USERS DU
WHERE DS.PRIVILEGE = 'RESTRICTED SESSION'
AND DS.GRANTEE = DU.USERNAME;


SELECT 'ALTER SYSTEM KILL SESSION ''' || SID || ',' || SERIAL# ||''' IMMEDIATE;'
FROM V$SESSION
WHERE 
TYPE <> 'BACKGROUND'
AND
USERNAME NOT IN
(SELECT DR.GRANTEE
FROM DBA_SYS_PRIVS DS, DBA_ROLE_PRIVS DR
WHERE DS.PRIVILEGE = 'RESTRICTED SESSION'
AND DS.GRANTEE = DR.GRANTED_ROLE
UNION
SELECT USERNAME
FROM DBA_SYS_PRIVS DS, DBA_USERS DU
WHERE DS.PRIVILEGE = 'RESTRICTED SESSION'
AND DS.GRANTEE = DU.USERNAME);



SELECT * FROM KILL_SESSION;

CREATE OR REPLACE VIEW KILL_SESSION
AS
SELECT 'ALTER SYSTEM KILL SESSION ''' || SID || ',' || SERIAL# ||''' IMMEDIATE;' AS KILL_QUERY
FROM V$SESSION
WHERE 
TYPE <> 'BACKGROUND'
AND
USERNAME NOT IN
(SELECT DR.GRANTEE
FROM DBA_SYS_PRIVS DS, DBA_ROLE_PRIVS DR
WHERE DS.PRIVILEGE = 'RESTRICTED SESSION'
AND DS.GRANTEE = DR.GRANTED_ROLE
UNION
SELECT USERNAME
FROM DBA_SYS_PRIVS DS, DBA_USERS DU
WHERE DS.PRIVILEGE = 'RESTRICTED SESSION'
AND DS.GRANTEE = DU.USERNAME);

ALTER SYSTEM KILL SESSION '240,14168' IMMEDIATE;




