CREATE OR REPLACE VIEW WILILCE
(
	ILNO,
	ILISMI,
	ILCEISMI,
	ILCE_SAYISI,
	ILILCE
) AS
SELECT A.IL_NO,  
	A.ISIM ILISMI, 
	NULL ILCEISMI, 
	TO_CHAR((SELECT COUNT(*) FROM ILCELER B WHERE A.IL_NO = B.IL_NO)) ILCE_SAYISI, 
	'IL' ILILCE 
FROM ILLER A
UNION
SELECT IL_NO, 
	NULL, 
	ISIM, 
	' ', 
	'ILCE' 
FROM ILCELER;


SELECT DECODE(ILISMI,NULL, NULL, ILNO) ILNO, ILISMI, ILCEISMI, ILCE_SAYISI FROM WILILCE
WHERE ILNO = 34;
ORDER BY ILNO, ILCEISMI;
